### ISSUE TITLE
Linux build fail

### ISSUE THREAD

**Issue by wanghongenpin** [abner/flutter_js#138]
flutter_js: ^0.8.0
Linux:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

plugins/flutter_js/CMakeFiles/flutter_js_plugin.dir/flutter_js_plugin.cc.o -MF plugins/flutter_js/CMakeFiles/flutter_js_plugin.dir/flutter_js_plugin.cc.o.d -o
plugins/flutter_js/CMakeFiles/flutter_js_plugin.dir/flutter_js_plugin.cc.o -c
/home/wanghe/network-proxy-flutter/linux/flutter/ephemeral/.plugin_symlinks/flutter_js/linux/flutter_js_plugin.cc
[   +3 ms] as: unrecognized option '--gdwarf-5'
[+1181 ms] [7/17] Building CXX object plugins/proxy_manager/CMakeFiles/proxy_manager_plugin.dir/proxy_manager_plugin.cc.o
[ +252 ms] [8/17] Building CXX object plugins/screen_retriever/CMakeFiles/screen_retriever_plugin.dir/screen_retriever_plugin.cc.o
[   +1 ms] ninja: build stopped: subcommand failed.
[  +57 ms] Building Linux application... (completed in 11.6s)
[+25997 ms] Exception: Build process failed
[  +16 ms] "flutter run" took 40,442ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

**Comment by crisperit** [comment]
Same problem - have you found some solution?

**Comment by wanghongenpin** [comment]
> Same problem - have you found some solution?

use Ubuntu 20.xx
