### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'JavaScriptCore.framework/JavaScriptCore' on iOS release TestFlight build

### ISSUE THREAD

**Issue by hpelitebook745G2** [abner/flutter_js#151]
I'm using `flutter_js: ^0.8.0` and here's my flutter version:
```
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (3 weeks ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3
```

It works fine in my emulator and actual iPhone but when I archive and upload to TestFlight, my app only shows white screen. I wrapped my main.dart with `try catch` and displayed Error widget that prints error and stacktrace.

Apparently, I got the error:
```
Invalid argument(s): Failed to load dynamic library
'JavaScriptCore.framework/JavaScriptCore':
dlopen (JavaScriptCore.framework/JavaScriptCore, 0x0001): tried:
'JavaScriptCore.framework/JavaScriptCore' (relative path not allowed in hardened program), '/private/preboot/Cryptexes/ OSJavaScriptCore.framework/JavaScriptCore' (no such file), '/usr/ lib/swift/JavaScriptCore.framework/JavaScriptCore' (no such file, not in dyld cache), 'private/preboot/Cryptexes/OS/usr/lib/swift/ JavaScriptCore.framework/JavaScriptCore' (no such file), '/private/ var/containers/Bundle/Application/ABC123/Test.app/Frameworks/ JavaScriptCore.framework/JavaScriptCore' (no such file), /privatel var/containers/Bundle/Application/ABC123/Test.app/Frameworks/ JavaScriptCore.framework/JavaScriptCore' (no such file), '/usr/lib/ JavaScriptCore framework/JavaScriptCore' (no such file, not in dyld cache), 'JavaScriptCore.framework/JavaScriptCore' (relative path not allowed in hardened program)
```
(Incomplete) Stacktrace:
```
#0 _open (dart:ffi-patch/ffi_dynamic_library_patch.dart: 11)
#1 new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2 JscFfi.lib (package:flutter_js/javascriptcore/binding/jsc_ffi.dart:7)
#3 jSContextGroupCreate (package:flutter_js/javascriptcore/binding/is_context_ref.dart)
#4 new JavascriptCoreRuntime (package:flutter_js/javascriptcore/iscore_runtime.dart)
#5 getJavascriptRuntime (package:flutter_js/flutter_js.dart:45)
#6 SampleClass._initJsRuntime (package:abc_sample_class/src/sample_class.dart:351)
#7 SampleClassMobile.init (package:abc_sample_class_mobile/src/sample_class.dart:324)
#8 WalletService.init (package:avmp_wallet_service/src/wallet_service.dart:52)
#9 ServiceRegistry.registerAll.<anonymous closure>(package:abc_app/src/service_registry.dart:203)
#10 _GetitImplementation.register.<anonymous closure>(package:get_it/get_it_impl.dart:1256)
#11 Future._propagateToListeners.handleValueCallback(dart:async/future_impl.dart:847)
#12 Future._propagateToListeners (dart:async/ future_impl.dart:876)
```

This is a complete blocker before my app is published to App Store. If someone encounters or knows how to fix is, please let me know. Thanks a lot!

**Comment by hectorAguero** [comment]
Duplicated of this https://github.com/abner/flutter_js/issues/126, I had the same error and used the fork mentioned there

**Comment by abner** [comment]
Fixed in `flutter_js: ^0.8.1`
