### ISSUE TITLE
 Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)

### ISSUE THREAD

**Issue by emilekm2142** [abner/flutter_js#34]
Whenever I try to do a HTTP request I get the following exception. Setting the breakpoint on the line `     var promiseResult = await flutterJs.handlePromise(initres);` indicates that the error occurs before executing the Dart promise with `await`. That is - I get the exception when trying to call ` flutterJs.handlePromise(initres)`
```
E/flutter (16365): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
E/flutter (16365): TypeError: not a function
E/flutter (16365): ^
E/flutter (16365): 
E/flutter (16365): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:5)
E/flutter (16365): #1      int._parseRadix (dart:core-patch/integers_patch.dart:157:16)
E/flutter (16365): #2      int._parse (dart:core-patch/integers_patch.dart:100:12)
E/flutter (16365): #3      int.parse (dart:core-patch/integers_patch.dart:63:12)
E/flutter (16365): #4      HandlePromises._doHandlePromise (package:flutter_js/extensions/handle_promises.dart:108:26)
E/flutter (16365): #5      HandlePromises.handlePromise (package:flutter_js/extensions/handle_promises.dart:97:14)
E/flutter (16365): #6      _MyAppState.load (package:com.example.flutter/main.dart:38:42)
E/flutter (16365): <asynchronous suspension>
I/flutter (16365): RESPONSE TEXT: {"userId":1,"id":1,"title":"delectus aut autem","completed":false}
```

Code generating the error
```js
 var initres =await flutterJs.evaluateAsync("fetch('https://jsonplaceholder.typicode.com/todos/1').then(response => response.json()).then(data => console.log(data));");
     var promiseResult = await flutterJs.handlePromise(initres);
    print(promiseResult);
```

It is weird but the request is done successfuly as the response text is printed.

It would be great if you added an example how to handle promises and make requests with fetch.

**Comment by abner** [comment]
When you setup a `then` callback to print the data returned, you shoud also return the data in  this callback, otherwise the returned `Promise` will evaluate to `undefined`.

I wil write better documentation very soon. I'm open for contributions also.

Regards!
