### ISSUE TITLE
Failed to load dynamic library (test/build/libffiquickjs.so)

### ISSUE THREAD

**Issue by glWesley** [abner/flutter_js#36]
when depending on flutter_js in **our own** test project, there would be a crash as follow:
```
When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      _qjsLib (package:flutter_js/quickjs/ffi.dart:121:30)
#3      _qjsLib (package:flutter_js/quickjs/ffi.dart)
#4      _jsNewRuntime (package:flutter_js/quickjs/ffi.dart:161:19)
#5      _jsNewRuntime (package:flutter_js/quickjs/ffi.dart)
#6      jsNewRuntime (package:flutter_js/quickjs/ffi.dart:204:14)
#7      QuickJsRuntime2._ensureEngine (package:flutter_js/quickjs/quickjs_runtime2.dart:51:16)
#8      QuickJsRuntime2.evaluate (package:flutter_js/quickjs/quickjs_runtime2.dart:165:5)
#9      QuickJsRuntime2.initChannelFunctions (package:flutter_js/quickjs/quickjs_runtime2.dart:230:9)
#10     JavascriptRuntime.init (package:flutter_js/javascript_runtime.dart:63:5)
#11     new QuickJsRuntime2 (package:flutter_js/quickjs/quickjs_runtime2.dart:46:10)
#12     getJavascriptRuntime (package:flutter_js/flutter_js.dart:37:15)
#13     new JSEngine (package:xml_widget/js_engine.dart:12:21)
#14     main.<anonymous closure> (file:///home/wesley/WorkPlace/projects/flutter/durian/xml_widget/test/test_engine.dart:31:20)
#15     main.<anonymous closure> (file:///home/wesley/WorkPlace/projects/flutter/durian/xml_widget/test/test_engine.dart:7:34)
#16     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```
That's because of condition load path:
```
final DynamicLibrary _qjsLib = Platform.environment['FLUTTER_TEST'] == 'true'
    ? (Platform.isWindows
        ? DynamicLibrary.open('test/build/Debug/ffiquickjs.dll')
        : Platform.isMacOS
            ? DynamicLibrary.open('test/build/libffiquickjs.dylib')
            : DynamicLibrary.open('test/build/libffiquickjs.so'))
    : (Platform.isWindows
        ? DynamicLibrary.open('flutter_js_plugin.dll')
        : Platform.isAndroid
            ? DynamicLibrary.open('libfastdev_quickjs_runtime.so')
            : DynamicLibrary.process());
```
Actually, it should load from lib directly.
Thanks!

**Comment by abner** [comment]
fixed at 0.4.0+3

Added instructions how to setup to test find the dynamic libraries at https://github.com/abner/flutter_js#unit-testing-javascript-evaluation
