### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'JSInvokable' in type cast

### ISSUE THREAD

**Issue by cdoco** [abner/flutter_js#65]
Flutter 2.7.0-3.0.pre
Dart 2.15.0
flutter_js 0.5.0+3

```
E/flutter ( 4836): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'JSInvokable' in type cast
E/flutter ( 4836): #0      QuickJsRuntime2.initChannelFunctions (package:flutter_js/quickjs/quickjs_runtime2.dart:231:24)
E/flutter ( 4836): #1      JavascriptRuntime.init (package:flutter_js/javascript_runtime.dart:63:5)
E/flutter ( 4836): #2      new QuickJsRuntime2 (package:flutter_js/quickjs/quickjs_runtime2.dart:46:10)
E/flutter ( 4836): #3      getJavascriptRuntime (package:flutter_js/flutter_js.dart:36:15)
E/flutter ( 4836): #4      JavascriptRuntimeService.init (package:flutter_test/services/javascript_runtime.dart:12:18)
E/flutter ( 4836): #5      Global.init.<anonymous closure> (package:flutter_test/global.dart:27:57)
E/flutter ( 4836): #6      GetInstance.putAsync (package:get/get_instance/src/get_instance.dart:62:32)
E/flutter ( 4836): #7      Inst.putAsync (package:get/get_instance/src/extension_instance.dart:44:21)
E/flutter ( 4836): #8      Global.init (package:flutter_test/global.dart:27:15)
E/flutter ( 4836): <asynchronous suspension>
E/flutter ( 4836): 
```

**Comment by narumishi** [comment]
Same here, it seems changes in flutter 2.7, I need to downgrade to 2.6 to bypass the error.
