### ISSUE TITLE
Error in Linux Desktop

### ISSUE THREAD

**Issue by inoerp** [abner/flutter_js#78]
Getting below error on Linux Desktop. 
Did not find any specific error for flutter js. However, the app works fine if I remove this package.
I am using flutter_js: ^0.5.0+5

```
[+10312 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 28,056ms.
[  +24 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

**Comment by xwzliang** [comment]
Hey @inoerp, did you find the solution for this? I got the same problem…

**Comment by inoerp** [comment]
working fine with flutter_js: ^0.5.0+3

**Comment by xwzliang** [comment]
Thanks for your help! Things might be a bit different for me, the cause of problem seems to have something to do with the OS, I was on Ubuntu 21.10 and couldn’t get it work with any version, always got error “as: unrecognized option '--gdwarf-5'”. Then I switched back to Ubuntu 20.04, and everything works fine.
